#!/usr/bin/env php
<?php

/*
 * This file is part of Contao Package Indexer.
 *
 * Copyright (c) 2017 Contao Association
 *
 * @license LGPL-3.0+
 */

use Contao\PackageIndexer\Command\IndexCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

set_time_limit(0);
ini_set('display_errors', true);
ini_set('display_startup_errors', true);

require __DIR__.'/vendor/autoload.php';

if (file_exists(__DIR__.'/.env')) {
    (new Dotenv())->load(__DIR__.'/.env');
}

$application = new Application('Contao Package Indexer', 'dev');
$application->add(new IndexCommand());
$application->setDefaultCommand('index', true);
/** @noinspection PhpUnhandledExceptionInspection */
$application->run();
